name: SonarQube Analysis
on:
  push:
    branches:
      - main # Hoặc tên branch chính của bạn (master/develop)
  pull_request:
    types: [ opened, synchronize, reopened ] # Thêm phân tích Pull Request (nếu SonarQube hỗ trợ)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        run: mvn sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Cần cho việc trang trí PR
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}